/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "It seems like you're one of the few visiting this page with JavaScript disabled or not available.\n                <br/>Since this page is a browser game and thus utilizes JavaScript, displaying this notice is all I can do unless you enable it.": "看起来你是少数几个访问这个页面禁用或不可用JavaScript的人之一。\n <br/>因为这个页面是一个浏览器游戏，因此使用JavaScript，显示这个通知是我所能做的，除非你启用它。",
    "Bulk Energy": "能量体积",
    "Cards": "卡片",
    "Cards left": "剩余卡片",
    "Click this big \"Draw\" button below to start": "点击下方这个大大的“抽卡”按钮以开始",
    "Collection": "收藏",
    "Draw": "抽卡",
    "drawing": "抽卡",
    "draws": "抽卡次数",
    "free": "免费",
    "Free Draws": "免费抽卡",
    "I ain't reading allat": "我根本没在看书",
    "Infobook": "信息手册",
    "Marketplace": "市场",
    "Next": "下一步",
    "One Trillion": "一万亿",
    "Points": "点数",
    "Seems like there isn't anything here...": "好像这里什么都没有…",
    "Shreds": "碎片",
    "some of them!": "其中一些！",
    "You've got": "你得到了",
    "“Produced for the almighty Omega Cards game, these cards are actually vouchers for you to spend more money to draw more cards... after you use up all your one trillion free card draws, at least. They are too happy about giving people trillions of free card draws, in fact, everyone are“": "“这些卡片是为全能的 欧米伽卡牌 游戏制作的，实际上是你花更多钱抽更多卡的凭证……至少在你用完所有的1万亿免费抽卡之后。他们对给人们提供数万亿的免费抽奖太高兴了，事实上，每个人都是这样。”",
    "(you've drawn": "(你已经抽取了",
    "(game saved)": "(游戏已保存)",
    "CARDS": "卡片",
    "Card Images": "卡片图片",
    "Local Save": "本地保存",
    "Hard Reset": "硬重置",
    "Disabled": "已禁用",
    "Enabled": "已启用",
    "Chinese": "中文",
    "Continue": "继续",
    "ago)": "前)",
    "About & Credits": "关于 & 鸣谢",
    "(last saved": "(上次保存",
    "A Single Point": "单点",
    "EDITION": "版本",
    "Gain": "获得",
    "Fusion cost:": "融合成本:",
    "OMEGA CARDS": "欧米伽卡牌",
    "Number Format": "数值格式",
    "Korean": "朝鲜文",
    "Manual Save": "手动保存",
    "Other": "其他",
    "Other other": "其他的其他",
    "points per draw.": "点数每次抽卡。",
    "Roll": "重掷",
    "Pull": "拉",
    "Preferences": "首选项",
    "Save Management": "保存管理",
    "SI Prefixes": "SI前缀",
    "Spin": "转动",
    "Summon": "召唤",
    "Upgrade cost:": "升级成本:",
    "TRADING CARD GAME": "交易卡游戏",
    "Verb": "动词",
    "PACK OF": "卡包包含",
    "Insufficient Points.": "点数不足。",
    "Insufficient copies.": "副本不足。",
    "FIRST": "第一",
    "Import/Export Save": "导入/导出存档",
    "Alphabet": "字母",
    "In cooldown": "冷却中",
    "Another Gacha Game to the Pile": "另一款扭蛋游戏",
    "extra copies)": "额外的副本)",
    "\"A Single Point\" extra copies": "\“单点\“额外的副本",
    "Background Music": "背景音乐",
    "Badge obtained:": "获得徽章:",
    "Change the verb associated with drawing cards, in places such as the game title and item descriptions.": "在游戏标题和物品描述等地方更改与抽卡相关的动词。",
    "(you have": "(你有",
    "“If you haven't noticed it yet, you can click the pack while it's breaking to break it faster“": "“如果你还没有注意到它，你可以在它破裂的时候点击它，以便更快地破坏它。”",
    "“Restock faster with our new fast delivery service—applied to all orders 1 card and above!“": "“使用我们新的快速送货服务更快地补充库存，适用于所有1卡及以上订单！””",
    "\"Scissors\" extra copies": "“剪刀”额外的副本",
    "“That one square that is programmed to be picked 99% of the time“": "“这个方块被设定为99%的几率被选中”",
    "“The world's most generic currency. It is generic enough to be assigned any use case imaginable“": "“世界上最通用的货币。它足够通用，可以分配给任何可以想象的用例。”",
    "“To explain what half a point even is, we'll need to talk about parallel universes-“": "“为了解释半点到底是什么，我们需要谈谈平行宇宙——”",
    "BONUS ITEMS": "奖励物品",
    "cooldown speed.": "冷却速度。",
    "Fast Delivery": "快速交付",
    "Half A Point": "半点",
    "Half a Point": "半点",
    "INCLUDED": "包含在内",
    "No effect.": "没有效果。",
    "pack breaking speed.": "拆包速度。",
    "points per spin.": "点数每次转动。",
    "Randomly gain zero to": "随机获得0到",
    "Scissors": "剪刀",
    "The Nothing Square": "虚无方块",
    "(Note: this game auto-saves after a minute since the last save and on certain events such as after a draw and when a setting is changed)": "（注：这个游戏会在最后一次保存的一分钟后自动保存，在某些事件，如平局后和设置改变时自动保存）",
    "Alternatively, paste your save there and press \"Import from Text Box\" to load the save.": "或者，将你的保存粘贴在那里，然后按“从文本框导入”来加载保存。",
    "Click to upgrade.": "单击升级。",
    "Close": "关闭",
    "Copy to Clipboard": "复制到剪贴板",
    "Download File": "下载文件",
    "Game saved": "游戏已保存",
    "Import from Text Box": "从文本框导入",
    "It is now safe to close this tab.": "现在可以安全地关闭这个选项卡了。",
    "The text box below contains your save data. Copy your save and keep it somewhere safe.": "下面的文本框包含您的保存数据。复制你的存档并保存在安全的地方。",
    "Upload File": "上传文件",
    "Copied": "已复制",
    "Save data copied to clipboard.": "存档已复制到剪贴板。",
    "Safe and Sound": "安然无恙",
    "\"Half A Point\" extra copies": "\“半点\”额外的副本",
    "\"The Nothing Square\" extra copies": "“虚无广场”额外副本",
    "“Well, if you want to use up all of those one trillion card draws you'll need to start drawing multiple of them at once, you know?“": "“嗯，如果你想用完所有的一万亿张卡，你就需要开始一次抽好几张卡，你知道吗？””",
    "base bulk. Base bulk increase the amount of draws you make at once.": "基础体积。基础体积增加你一次抽取卡片的数量。",
    "Card Pack": "卡包",
    "Downloading save...": "正在下载保存…",
    "This card can not be upgraded.": "此卡无法升级。",
    "until cap)": "直到封顶)",
    "\"Bigger Wrap\" extra copies": "“更大的包装”额外副本",
    "\"Card Pack\" extra copies": "\”卡包\“额外的副本",
    "“Find cards that can't be found from drawing, and probably spend all of your money trying to out-bid the highest bidder“": "“找到抽卡时找不到的卡，可能会花光你所有的钱，试图赢过出价最高的人。”",
    "“Incremental games, also known as idle games“": "“增量游戏，也被称为放置游戏”",
    "\"Self-Filling Pack\" extra copies": "“自动填充包”额外的副本",
    "“Used as Omega Cards' loyalty program currency to allow you to trade multiple cards at once“": "“用作 欧米伽卡牌 的忠诚计划货币，允许您一次交易多张卡”",
    "“You can idle for real this time“": "“这次你真的可以闲下来了。”",
    "Bigger Wrap": "更大的包装",
    "bulk energy cap. Bulk energy production past the energy cap are slowed down.": "大能量上限，超过能量上限的大能量生产速度会减慢。",
    "bulk power. Bulk power passively generates bulk energy.": "大功率。大功率被动地产生大容量能量。",
    "In-Game Shop": "游戏内商店",
    "Self-Filling Pack": "自动填充包装",
    "Unlock the Marketplace.": "解锁市场。",
    "“Please note that StackRAR is not a free card. After a 40 day trial period you must either buy a license or burn this card off of your collection“": "“请注意，堆叠压缩 不是一张免费卡。在40天的试用期之后，您必须购买许可证或将这张卡从您的收藏中删除。",
    "(card not yet owned)": "（卡尚未拥有）",
    "bulk draw limit.": "批量抽取上限",
    "efficiency)": "效率)",
    "Group together duplicate cards in the draw view, though the compression halves your card revealing speed in the process. Also remove the": "在抽牌视图中将重复的卡组在一起，尽管压缩过程中的卡显示速度会减半。同时去掉",
    "Purchase cost:": "购买成本：",
    "StackRAR": "堆叠压缩",
    "\"Fast Delivery\" extra copies": "“快速交付”额外副本",
    "Click to fuse.": "点击融合。",
    "Click to purchase.": "点击购买。",
    "Four-Leaf Clover": "四叶草",
    "LIMITED EDITION": "限量版",
    "Point Multiplier": "点数乘数",
    "point multiplier.": "点数乘数。",
    "SPECIAL EXTRA": "特殊额外",
    "This card can not be fused.": "这张卡不能融合。",
    "“Act as if nothing has ever happened“": "“装作什么都没发生过”",
    "“Every incremental game needs exponential growth, a generic currency needs a generic multiplier upgrade“": "“每一款增量游戏都需要指数级增长，一种通用货币需要一种通用的乘数升级。”",
    "Duplicate cards that are useless are shredded into a new currency called Shreds, including crowned cards and cards with max stars.": "重复的无用卡将被粉碎成一种新的货币，称为碎片，包括皇冠卡和最大星星卡。",
    "Shredder": "碎纸机",
    "“The card packs got some endurance training! Now they are harder to break into, but the contents are increased!“": "“卡包得到了一些耐力训练！现在更难进入了，但是里面的东西增加了！”",
    "card multiplier, but": "卡片乘数, 但是",
    "Endurance Training": "耐力训练",
    "cooldown duration and pack breaking duration.": "冷却时间和拆包时间。",
    "\"Bulkier Card Packs\" extra copies": "“体积更大的卡片包”额外的副本",
    "“The bulkier, the better“": "“体积越大越好”",
    "base bulk, but": "基础体积，但是",
    "Bulkier Card Packs": "更大的卡片包",
    "cooldown duration.": "冷却持续时间。",
    "bulk power, but": "大功率，但是",
    "Card Opener Factory": "开卡器工厂",
    "“Produces large quantity of card openers“": "“生产大量的开卡器”",
    "\"Endurance Training\" extra copies": "“耐力训练“额外的副本",
    "\"Card Opener Factory\" extra copies": "“开卡器工厂”额外副本",
    "\"Point Multiplier\" extra copies": "“点数乘数”额外的副本",
    "\"Recycling\" extra copies": "“回收”额外的副本",
    "“Remains of excess cards, reduced to atoms. These cards almost have no trade value (except for the few": "”剩余的卡片，被分解成原子。这些卡片几乎没有交易价值（除了少数）“",
    "“Reusing cards to open more cards is a good idea actually“": "“重复使用卡片来打开更多的卡片实际上是个好主意。”",
    "bulk power.": "大功率。",
    "cards), so people are inventing new ways to use them, such as shredding them to use as a new upgrade currency“": "所以人们开始发明新的使用方式，比如将它们撕碎作为新的升级货币使用。”",
    "Insufficient Shreds.": "碎片不足。",
    "Recycling": "回收",
    "\"Composter\" extra copies": "\“堆肥器\”额外的副本",
    "“Recycle even harder with this composter designed to make a metric-scrap-ton of cards“": "“有了这个设计用来制造吨级卡片的堆肥器，回收更加困难了”",
    "bulk energy cap.": "能量体积上限。",
    "Composter": "堆肥器",
    "\"Epic Shredding Machine\" extra copies": "“史诗碎纸机”额外副本",
    "“Instead of using a small office-made shredder, why not use the giant ones made for ASMR videos on the internet?“": "“与其使用办公室制造的小型碎纸机，为什么不使用互联网上为ASMR视频制作的巨型碎纸机呢？””",
    "\"Money Press\" extra copies": "\“货币印刷机”额外的副本",
    "“Press some of your shreds into money. This is precisely how legal money are made too, people won't even be able to notice a difference“": "“把你的一些碎片压成钞票。这也是合法货币的制造方式，人们甚至不会注意到其中的区别。”",
    "Epic Shredding Machine": "史诗碎纸机",
    "Money Press": "货币印刷机",
    "shred multiplier.": "分解乘数。",
    "\"Amazing Shredding Moments\" extra copies": "“神奇分解时刻”额外的副本",
    "Amazing Shredding Moments": "神奇分解时刻",
    "“Apparently people on the internet love watching things being shredded to pieces! You figure out you could record your Epic Shredding Machines shredding cards and upload it to PipeTube to earn some sweet, sweet ad revenue in the process“": "“显然，互联网上的人们喜欢看东西被撕成碎片！你发现你可以记录下你的史诗撕碎机，并将其上传到PipeTube，在这个过程中赚取一些甜蜜的广告收入。”",
    "“Erm ackstually 🤓“": "“嗯，当然啦🤓”",
    "System 2": "系统 2",
    "Unlock the Infobook. View your stats and other things, though with a price...": "解锁信息手册。查看你的统计数据和其他东西，尽管有价格…",
    "The thrilling experience of not knowing what items you'll get, the satisfying feeling when you get a rare draw, the flexibility and easiness to add gacha mechanics to every game in existence...": "不知道自己会得到什么道具的兴奋体验，获得罕见的吸引力时的满足感，在现有游戏中添加扭蛋机制的灵活性和易用性……",
    "card.": "卡片。",
    "Cards drawn": "抽取的卡片",
    "Base bulk": "基础体积",
    "Base gain": "基础增益",
    "Bulk power": "大功率",
    "card multi": "卡片乘以",
    "Card multiplier": "卡片乘数",
    "appear chance": "出现几率",
    "Intro": "介绍",
    "lot": "很多",
    "Story": "故事",
    "Skills": "技能",
    "Sun Power": "太阳能",
    "Sun Power gain": "太阳能增益",
    "Skill reactions": "技能反应",
    "Random gain": "随机增益",
    "\"Burst\" use count": "\“爆裂”使用计数",
    "\"Fertilizer\" use count": "“肥料”使用计数",
    "\"Freeze Drop\" use count": "“冰冻掉落”使用次数",
    "\"Photosynthesis\" use count": "“光合作用”使用计数",
    "\"Simplification\" use count": "\“简化\”使用计数",
    "(locked badge)": "（锁定徽章）",
    "(obtained badge)": "(获得徽章)",
    "All Power mult": "全部力量乘数",
    "Badges": "徽章",
    "Crowned card multi": "皇冠卡乘数",
    "Draw cards for the first time.": "首次抽卡",
    "Enter": "输入",
    "Faction": "派系",
    "Finally I can see what I'm doing!": "我终于明白我在做什么了！",
    "Fire Power": "火之力",
    "Fire Power gain": "火之力增益",
    "Gacha gaming has become a way of life.": "Gacha游戏已经成为一种生活方式。",
    "Gain on draw": "抽卡增益",
    "Gallery": "图鉴",
    "General": "概况",
    "It's the fact that...": "事实是……",
    "Just throw it away": "只是把它扔掉",
    "Leaf Power": "叶之力",
    "Leaf Power gain": "叶之力增益",
    "Luck or Dedication?": "运气还是奉献？",
    "Manually save your game data to the cloud, or export your save.": "手动保存你的游戏数据到云端，或者导出你的保存。",
    "Moon Power": "月之力",
    "Moon Power gain": "月之力能量增益",
    "Multiplier": "乘数",
    "Obtain an": "获得一个",
    "Of course, since the market has become diluted with so many games, they need a way to introduce itself to players and prove that they're worth their time.": "当然，由于市场上的游戏越来越多，他们需要一种向玩家介绍自己的方式，并证明自己值得他们花时间。",
    "of money.": "的钱。",
    "People have found gacha games to be the best way to pass time, for casual players and the more competitive-minded players alike.": "人们发现扭蛋游戏是消磨时间的最佳方式，对休闲玩家和更具竞争意识的玩家来说都是如此。",
    "Plz plz plz Legendary": "传奇",
    "Polar Opposites": "两极对立",
    "Power chance": "力量几率",
    "The gacha gaming scene has grown into a multi-millillion-dollar worth industry, far greater than any entertainment scene's worth, combined.": "扭蛋游戏领域已经发展成为价值数百万美元的产业，远远超过任何娱乐领域的价值总和。",
    "Though, when people talk about gacha games, that's not the most significant point to keep in mind.": "然而，当人们谈论扭蛋游戏时，这并不是最重要的一点。",
    "Time played": "游戏时长",
    "To chase the money, billions of gacha games are coming out every single blink of an eye.": "为了赚钱，每一眨眼就有数十亿款扭蛋游戏问世。",
    "Ultra Rare or Uber Rare?": "超级稀有还是超级稀有？",
    "View your badges in-game.": "在游戏中查看你的徽章。",
    "Water Power": "水之力",
    "Water Power gain": "水之力增益",
    "Would you like to buy more draws?": "是否继续购买抽奖券",
    "“Apparently people on the internet love watching things being shredded to pieces! You figure out you could record your Epic Shredding Machines shredding cards and upload it to PipeTube to earn some sweet, sweet ad revenue in the process”": "“显然，互联网上的人们喜欢看东西被撕成碎片！你发现你可以记录下你的史诗撕碎机，并将其上传到PipeTube，在这个过程中赚取一些甜蜜的广告收入。”",
    "“A Single Point” extra copies": "“单点”额外的副本",
    "“Amazing Shredding Moments” extra copies": "“神奇的分解时刻”额外的副本",
    "“Bigger Wrap” extra copies": "“更大的包装”额外副本",
    "“Bulkier Card Packs” extra copies": "“更大的卡片包”额外的副本",
    "“Card Opener Factory” extra copies": "“开卡器工厂”额外副本",
    "“Card Pack” extra copies": "“卡包”额外的副本",
    "“Composter” extra copies": "“堆肥机”额外副本",
    "“Endurance Training” extra copies": "“耐力训练”额外的副本",
    "“Epic Shredding Machine” extra copies": "“史诗般的撕碎机”额外副本",
    "“Every incremental game needs exponential growth, a generic currency needs a generic multiplier upgrade”": "“每款渐进式游戏都需要指数级增长，通用货币需要通用乘数升级。”",
    "“Fast Delivery” extra copies": "“快速交货”额外的副本",
    "“Half A Point” extra copies": "“半点”额外的副本",
    "“Money Press” extra copies": "“货币印刷机”的额外副本",
    "“Point Multiplier” extra copies": "“点倍增器”额外的副本",
    "“Press some of your shreds into money. This is precisely how legal money are made too, people won't even be able to notice a difference”": "“把你的一些碎片压成钞票。这也是合法货币的制造方式，人们甚至不会注意到其中的区别。”",
    "“Produces large quantity of card openers”": "“生产大量的开卡器”",
    "“Recycling” extra copies": "“回收”额外的副本",
    "“Scissors” extra copies": "“剪刀”额外的副本",
    "“Self-Filling Pack” extra copies": "“自动填充包装”的额外副本",
    "“The bulkier, the better”": "“体积越大越好”",
    "“The Nothing Square” extra copies": "“虚无广场”额外的副本",
    "IF YOU CAN SEE THIS, CONTACT GAME AUTHOR": "如果你能看到这个，联系游戏作者",
    "“Act as if nothing has ever happened”": "“表现得好像什么都没发生过”",
    "“Erm ackstually 🤓”": "“嗯，当然啦🤓”",
    "“Find cards that can't be found from drawing, and probably spend all of your money trying to out-bid the highest bidder”": "“找到抽牌时找不到的牌，可能会花光你所有的钱，试图赢过出价最高的人。”",
    "“If you haven't noticed it yet, you can click the pack while it's breaking to break it faster”": "“如果你还没有注意到它，你可以在它破裂的时候点击它，以便更快地破坏它。”",
    "“Incremental games, also known as idle games”": "“增量游戏，也被称为空闲游戏”",
    "“Instead of using a small office-made shredder, why not use the giant ones made for ASMR videos on the internet?”": "“与其使用办公室自制的小型碎纸机，为什么不使用互联网上为ASMR视频制作的巨型碎纸机呢？”",
    "“Please note that StackRAR is not a free card. After a 40 day trial period you must either buy a license or burn this card off of your collection”": "“请注意，堆叠压缩 不是一张免费卡。在40天的试用期之后，您必须购买许可证或将这张卡从您的收藏中删除。",
    "“Recycle even harder with this composter designed to make a metric-scrap-ton of cards”": "“使用这个设计用于制造吨卡片的堆肥机回收更加困难。”",
    "“Restock faster with our new fast delivery service—applied to all orders 1 card and above!”": "“使用我们新的快速送货服务更快地补充库存，适用于所有1卡及以上订单！”",
    "“Reusing cards to open more cards is a good idea actually”": "“重复使用卡片来打开更多的卡片实际上是个好主意。”",
    "“That one square that is programmed to be picked 99% of the time”": "“这个方块被设定为99%的几率被选中”",
    "“The card packs got some endurance training! Now they are harder to break into, but the contents are increased!”": "“卡组得到了一些耐力训练！现在它们更难进入了，但里面的东西却增加了！”",
    "“To explain what half a point even is, we'll need to talk about parallel universes-”": "“为了解释半点到底是什么，我们需要谈谈平行宇宙——”",
    "“Well, if you want to use up all of those one trillion card draws you'll need to start drawing multiple of them at once, you know?”": "“嗯，如果你想用完所有的一万亿张牌，你就需要开始一次抽好几张牌，你知道吗？”",
    "“You can idle for real this time”": "“这次你真的可以闲下来了。”",
    "+ card mult": "+ 卡片乘数",
    "Crowned card mult": "皇冠卡乘数",
    "Dice Extractor": "骰子提取器",
    "“Press some of your shreds into money. This is precisely how legal money is made too, people won't even be able to notice a difference”": "“把你的一些碎片压成钞票。这也是合法货币的制造方式，人们甚至不会注意到其中的区别。”",
    "“Restock faster with our new fast delivery service — applied to all orders 1 card and above!”": "“使用我们新的快速送货服务更快地补充库存-适用于所有1卡及以上订单！”",
    "“The world's most generic currency. It is generic enough to be assigned any use case imaginable”": "“世界上最通用的货币。它足够通用，可以分配给任何可以想象的用例。”",
    "“Used as Omega Cards' loyalty program currency to allow you to trade in multiple card draws at once”": "“作为欧米伽卡会员计划货币，可同时兑换多张抽卡”",
    "cards), so people are inventing new ways to use them, such as shredding them to use as a new upgrade currency”": "所以人们开始发明新的使用方式，比如将它们撕碎作为新的升级货币使用。”",
    "'s effect by": "的效果",
    "“A Pair of Points” extra copies": "“一对点数”额外副本",
    "“This is called a line”": "“这叫做一条线”",
    "A Pair of Points": "一对点数",
    "Raise the level in": "提升等级在",
    "“Let the pips on the die guide you”": "“让骰子上的点来指引你”",
    "Overused Faction System": "过度使用派系系统",
    "Unlock Factions. Use factioned draws to get factioned currencies and faction-specific cards. (Factioned currency has a rare chance to appear.)": "解锁派系。使用派系抽卡来获得派系货币和派系专用卡牌。（派系化货币出现的几率极低。）",
    "“Long ago, the five factions lived together in harmony. Then, everything changed when the fire faction attacked.”": "“很久以前，五个派系和睦相处。然后，当火派发动袭击时，一切都改变了。”",
    "“A perfectly generic card that boosts the perfectly generic currency, the genericness is getting too perfect to handle”": "“一张完美的通用卡，可以提升完美的通用货币，通用性变得太完美了，无法处理”",
    "“Dice Extractor” extra copies": "“骰子提取器”额外副本",
    "“Perfectly Generic Card” extra copies": "“完美通用卡”额外副本",
    "Max star reached.": "已满星。",
    "Perfectly Generic Card": "完美通用卡",
    "Card Warehouse": "卡片仓库",
    "“Card Warehouse” extra copies": "“卡片仓库”额外副本",
    "“At this rate you will need to get yourself a bigger room just so you can store all your cards”": "“照这样下去，你得给自己找个更大的房间，以便存放你所有的卡片。”",
    "(Currently:": "(当前:",
    "“Royal Junk” extra copies": "“皇家垃圾”的额外副本",
    "“More valuable than regular junk”": "“比普通垃圾更有价值”",
    "Gain more Shreds based on the total amount of crowned cards you have in your collection.": "根据你收集的皇冠卡的总数获得更多的碎片。",
    "Royal Junk": "皇家垃圾",
    "shred gain)": "碎片增益)",
    "in": "需要",
    "English": "英文",
    "Language": "语言",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "© DUDUCAT TRADING CARD GAME CO. ": "© DUDUCAT 交易卡牌游戏有限公司",
    "stars)": "星)",
    "stars)\n                        (": "星)\n                        (",
    "\n                        (": "\n                        (",
    "\n                        \n                        (crowned card)\n                        ": "\n                        \n                        (皇冠卡片)\n                        ",
    "stars)\n                        (level": "星)\n                        (等级",
    "stars)\n                        ": "星)\n                        ",
    "/min)\n            (": "/分钟)\n            (",
    "johnvertisement": "johnvertisement",
    "Gacha": "扭蛋",
    "© DUDUCAT TRADING CARD GAME CO.": "© DUDUCAT 交易卡牌游戏公司。",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "(": "(",
    ")": ")",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Save data downloading as ": "存档数据将下载保存为文件 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^\+([\d\.,]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^\^([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^×([\d\.]+)e([\d\.,]+)$/,
    /^\+([\d\.]+)e([\d\.,]+)$/,
    /^\~([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^PACK OF (.+) CARDS$/, '一套 $1 张卡片'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)h ([\d\.]+)m$/, '$1 小时 $2 分'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^The year is ([\d\.,]+).$/, '这是 $1 年。'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);